### ISSUE TITLE
Error while reading pdf

### ISSUE THREAD

**Issue by deependersingla** [yob/pdf-reader#138]
Hello 

First off, thanks for writing this gem. I just started using it and is a major help for me in reading pdf. I am reading this pdf file:
https://s3.amazonaws.com/staging_accredible_api_evidence_items/files/1284/original/1418037672774_pdf-sample1.pdf?1418037684

But getting this error:
PDF::Reader::MalformedPDFError: PDF malformed, expected 'endobj' but found 96 instead

Any idea, How I can resolve this?

**Comment by yob** [comment]
I've confirmed this error is still happening on master when I attempt to extract text from the provided file.

Unfortunately I'm short on time at the moment, but I'll happily accept a patch.

[1418037672774_pdf-sample1.pdf](https://github.com/yob/pdf-reader/files/774245/1418037672774_pdf-sample1.pdf)

**Comment by yob** [comment]
Interesting! This is still an issue in the latest release (v2.9.0).

The problem is that object 95 is a stream and it's missing the `endobj` token after the `endstream` token. We strictly require `endobj` to be there, but I guess other readers don't. I confirmed it opens without error in firefox and evince.

I can't see any harm to gracefully ignoring the missing `endobj` token, I'll work on a minimal PDF with the same issue and write a spec for it.
